const modules = [
  { id: 'm1', name: '校园与方向', icon: '🧭', color: '#eeeaff', shade: '#ded7ff', words: [
    ['straight on', '直着走', '/streɪt ɒn/', 'Go straight on.'], ['left', '左边；向左', '/left/', 'Turn left at the school.'], ['right', '右边；向右', '/raɪt/', 'Turn right here.'], ['lost', '迷路的', '/lɒst/', 'I am lost.'], ['live', '居住', '/lɪv/', 'I live in Jinjiang.'], ['road', '路；道路', '/rəʊd/', 'This road is long.'], ['near', '接近；在……附近', '/nɪə(r)/', 'The park is near.'], ['supermarket', '超市', '/ˈsuːpəmɑːkɪt/', 'The supermarket is over there.'] ] },
  { id: 'm2', name: '购物小街', icon: '🛍️', color: '#fff1dc', shade: '#ffe0b2', words: [
    ['shop', '商店', '/ʃɒp/', 'Let’s go to the shop.'], ['buy', '买', '/baɪ/', 'I want to buy a book.'], ['food', '食物', '/fuːd/', 'The food is nice.'], ['tomato', '西红柿', '/təˈmɑːtəʊ/', 'These tomatoes are red.'], ['potato', '马铃薯', '/pəˈteɪtəʊ/', 'I like potatoes.'], ['egg', '鸡蛋', '/eɡ/', 'I eat an egg.'], ['flower', '花', '/ˈflaʊə(r)/', 'The flower is beautiful.'], ['need', '需要', '/niːd/', 'We need some milk.'] ] },
  { id: 'm3', name: '快乐活动', icon: '🎠', color: '#e2f8ef', shade: '#c5eedf', words: [
    ['playground', '操场', '/ˈpleɪɡraʊnd/', 'Let’s go to the playground.'], ['play', '玩；参加（运动）', '/pleɪ/', 'I play football.'], ['skip', '跳绳', '/skɪp/', 'Can you skip?'], ['run', '跑', '/rʌn/', 'Run fast!'], ['swim', '游泳', '/swɪm/', 'I can swim.'], ['ride', '骑', '/raɪd/', 'I ride a bike.'], ['fly', '放（风筝）', '/flaɪ/', 'Let’s fly a kite.'], ['time', '时间；次数', '/taɪm/', 'It is play time.'] ] },
  { id: 'm4', name: '数字乐园', icon: '🔢', color: '#e8f3ff', shade: '#cfe4ff', words: [
    ['one hundred', '一百', '/wʌn ˈhʌndrəd/', 'One hundred children.'], ['thirteen', '十三', '/ˌθɜːˈtiːn/', 'I have thirteen books.'], ['fourteen', '十四', '/ˌfɔːˈtiːn/', 'There are fourteen birds.'], ['fifteen', '十五', '/ˌfɪfˈtiːn/', 'Fifteen pencils, please.'], ['sixteen', '十六', '/ˌsɪksˈtiːn/', 'She is sixteen.'], ['seventeen', '十七', '/ˌsevənˈtiːn/', 'Seventeen apples.'], ['eighteen', '十八', '/ˌeɪˈtiːn/', 'Eighteen boys.'], ['nineteen', '十九', '/ˌnaɪnˈtiːn/', 'Nineteen girls.'] ] },
  { id: 'm5', name: '我的朋友', icon: '🤝', color: '#fae8f1', shade: '#f4cde0', words: [
    ['friend', '朋友', '/frend/', 'He is my friend.'], ['strong', '强壮的', '/strɒŋ/', 'The boy is strong.'], ['quiet', '安静的', '/ˈkwaɪət/', 'She is a quiet girl.'], ['cute', '可爱的', '/kjuːt/', 'The panda is cute.'], ['little', '小的', '/ˈlɪtl/', 'I have a little dog.'], ['a bit', '有一点', '/ə bɪt/', 'I am a bit shy.'], ['helpful', '有帮助的', '/ˈhelpfl/', 'My friend is helpful.'], ['naughty', '淘气的', '/ˈnɔːti/', 'The naughty cat runs away.'] ] },
  { id: 'm6', name: '音乐星球', icon: '🎵', color: '#f2edff', shade: '#dfd5ff', words: [
    ['music', '音乐', '/ˈmjuːzɪk/', 'I like music.'], ['listen', '听', '/ˈlɪsn/', 'Listen to the song.'], ['dance', '跳舞', '/dɑːns/', 'They dance well.'], ['far', '远的', '/fɑː(r)/', 'My school is far.'], ['can', '能够', '/kæn/', 'I can sing.'], ['really', '很；非常', '/ˈrɪəli/', 'It is really good.'], ['also', '也', '/ˈɔːlsəʊ/', 'I can also dance.'], ['then', '那么；然后', '/ðen/', 'Then let’s begin.'] ] },
  { id: 'm7', name: '节日时光', icon: '🎁', color: '#fff5cf', shade: '#f8e5a0', words: [
    ['festival', '节日', '/ˈfestɪvl/', 'Spring Festival is coming.'], ['Christmas', '圣诞节', '/ˈkrɪsməs/', 'Merry Christmas!'], ['Spring Festival', '春节', '/sprɪŋ ˈfestɪvl/', 'We like Spring Festival.'], ['present', '礼物', '/ˈpreznt/', 'This present is for you.'], ['card', '卡片', '/kɑːd/', 'I make a card.'], ['Chinese', '中国的；中国人', '/ˌtʃaɪˈniːz/', 'Chinese New Year is fun.'], ['give', '给', '/ɡɪv/', 'I give Mum a present.'], ['special', '特别的', '/ˈspeʃl/', 'It is a special day.'] ] },
  { id: 'm8', name: '运动公园', icon: '⚽', color: '#e1f8f1', shade: '#c2ecdf', words: [
    ['sport', '运动', '/spɔːt/', 'Sport is fun.'], ['basketball', '篮球', '/ˈbɑːskɪtbɔːl/', 'I play basketball.'], ['football', '足球', '/ˈfʊtbɔːl/', 'Football is my favourite.'], ['table tennis', '乒乓球', '/ˈteɪbl tenɪs/', 'We play table tennis.'], ['jump', '跳', '/dʒʌmp/', 'Jump high!'], ['fast', '快的', '/fɑːst/', 'The horse runs fast.'], ['high', '高地', '/haɪ/', 'The kite flies high.'], ['well', '好；熟练地', '/wel/', 'You play very well.'] ] },
  { id: 'm9', name: '每日习惯', icon: '🌈', color: '#e8edff', shade: '#d2dbff', words: [
    ['every day', '每天', '/ˈevri deɪ/', 'I read every day.'], ['often', '经常', '/ˈɒfn/', 'I often play games.'], ['sometimes', '有时', '/ˈsʌmtaɪmz/', 'Sometimes I watch TV.'], ['never', '从不', '/ˈnevə(r)/', 'I never swim here.'], ['clean', '打扫；干净的', '/kliːn/', 'I clean my room.'], ['sleep', '睡觉', '/sliːp/', 'I sleep at nine.'], ['before', '在……之前', '/bɪˈfɔː(r)/', 'Wash hands before dinner.'], ['after', '在……之后', '/ˈɑːftə(r)/', 'Play after school.'] ] },
  { id: 'm10', name: '天气预报', icon: '⛅', color: '#e5f7ff', shade: '#c8e8fa', words: [
    ['weather', '天气', '/ˈweðə(r)/', 'What is the weather like?'], ['sunny', '晴朗的', '/ˈsʌni/', 'It is sunny today.'], ['windy', '有风的', '/ˈwɪndi/', 'It is windy in Jinjiang.'], ['rain', '下雨；雨', '/reɪn/', 'It will rain tomorrow.'], ['snow', '下雪；雪', '/snəʊ/', 'It snows in winter.'], ['hot', '炎热的', '/hɒt/', 'It is hot today.'], ['cold', '寒冷的', '/kəʊld/', 'Put on your coat.'], ['tomorrow', '明天', '/təˈmɒrəʊ/', 'See you tomorrow.'] ] }
];

const allWords = modules.flatMap(m => m.words.map((w, index) => ({ module: m, index, english: w[0], chinese: w[1], phonetic: w[2], example: w[3], key: `${m.id}-${index}` })));
const state = { module: null, words: [], card: 0, flipped: false, quiz: null, quizScore: 0, quizStep: 0, sound: true, mastered: new Set(JSON.parse(localStorage.getItem('wordIslandMastered') || '[]')), review: new Set(JSON.parse(localStorage.getItem('wordIslandReview') || '[]')) };
const $ = (selector) => document.querySelector(selector);

function save() { localStorage.setItem('wordIslandMastered', JSON.stringify([...state.mastered])); localStorage.setItem('wordIslandReview', JSON.stringify([...state.review])); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 1900); }
function updateProgress() { const count = state.mastered.size; const total = allWords.length; $('#masteredCount').textContent = count; $('#wordTotal').textContent = total; $('#overallProgress').style.width = `${Math.round(count / total * 100)}%`; $('#progressLabel').textContent = count === 0 ? '刚刚启航' : count < 15 ? '正在出发' : count < 45 ? '乘风破浪' : count < total ? '单词小达人' : '全岛通关！'; $('#reviewBadge').textContent = state.review.size; }
function moduleMastered(module) { return module.words.filter((_, i) => state.mastered.has(`${module.id}-${i}`)).length; }
function renderModules(filter = '') { const q = filter.trim().toLowerCase(); const shown = modules.filter(m => !q || m.name.includes(q) || m.words.some(w => w[0].toLowerCase().includes(q) || w[1].includes(q))); $('#moduleGrid').innerHTML = shown.map(m => `<button class="module-card ${state.module?.id === m.id ? 'active' : ''}" data-module="${m.id}" style="--card:${m.color};--shade:${m.shade}"><span class="module-icon">${m.icon}</span><strong>${m.name}</strong><small>${m.words.length} 个单词</small><span class="module-progress">${moduleMastered(m)}/${m.words.length}</span></button>`).join('') || '<p>没有找到这个词，再换个关键词试试。</p>'; document.querySelectorAll('[data-module]').forEach(el => el.addEventListener('click', () => chooseModule(el.dataset.module)));
}
function chooseModule(id, reviewWords = null) { state.module = modules.find(m => m.id === id) || modules[0]; state.words = reviewWords || allWords.filter(w => w.module.id === state.module.id); state.card = 0; state.flipped = false; renderModules($('#searchInput').value); renderCard(); $('#learnZone').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function renderCard() { const word = state.words[state.card]; const card = $('#flashcard'); if (!word) { card.classList.add('empty'); return; } card.classList.remove('empty'); card.classList.toggle('flipped', state.flipped); $('#lessonTag').textContent = state.words.length === state.module.words.length ? state.module.name : '复习站'; $('#lessonTitle').textContent = `${state.module.icon} ${state.module.name}`; $('#lessonHint').textContent = '听发音，翻开卡片看中文，再判断自己记住了吗？'; $('#cardIndex').textContent = state.card + 1; $('#cardTotal').textContent = state.words.length; $('#wordEnglish').textContent = word.english; $('#wordChinese').textContent = word.chinese; $('#wordPhonetic').textContent = word.phonetic; $('#wordExample').textContent = word.example; }
function speakCurrent() { const word = state.words[state.card]; if (!word || !state.sound || !('speechSynthesis' in window)) return; speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(word.english); utterance.lang = 'en-US'; utterance.rate = .78; speechSynthesis.speak(utterance); }
function changeCard(direction) { if (!state.words.length) return; state.card = (state.card + direction + state.words.length) % state.words.length; state.flipped = false; renderCard(); speakCurrent(); }
function markWord(known) { const word = state.words[state.card]; if (!word) return; if (known) { state.mastered.add(word.key); state.review.delete(word.key); toast('太棒了！这个词点亮啦 ✨'); } else { state.review.add(word.key); state.mastered.delete(word.key); toast('已放进复习站，明天再见它！'); } save(); updateProgress(); renderModules($('#searchInput').value); renderReview(); if (state.card < state.words.length - 1) setTimeout(() => changeCard(1), 260); else renderCard(); }
function renderReview() { const words = allWords.filter(w => state.review.has(w.key)); $('#reviewList').innerHTML = words.length ? words.map(w => `<div class="review-word"><div><strong>${w.english}</strong><small>${w.chinese}</small></div><button data-review="${w.key}">去复习 →</button></div>`).join('') : '<div class="review-empty"><span>🧺</span>复习站还是空的。遇到不熟的词，就点“还不熟”放进来吧！</div>'; document.querySelectorAll('[data-review]').forEach(btn => btn.addEventListener('click', () => { const word = allWords.find(w => w.key === btn.dataset.review); switchTab('learn'); chooseModule(word.module.id, [word]); })); }
function switchTab(tab) { document.querySelectorAll('.tab').forEach(el => el.classList.toggle('active', el.dataset.tab === tab)); document.querySelectorAll('.panel').forEach(el => el.classList.remove('active')); $(`#${tab}Panel`).classList.add('active'); if (tab === 'review') renderReview(); }
function shuffled(items) { return [...items].sort(() => Math.random() - .5); }
function startQuiz() { const pool = state.module ? allWords.filter(w => w.module.id === state.module.id) : allWords; state.quiz = shuffled(pool).slice(0, Math.min(5, pool.length)); state.quizScore = 0; state.quizStep = 0; $('#quizStars').textContent = '☆ ☆ ☆ ☆ ☆'; renderQuestion(); }
function renderQuestion() { const word = state.quiz[state.quizStep]; if (!word) { $('#quizQuestion').textContent = `挑战完成！你答对了 ${state.quizScore} / ${state.quiz.length} 题`; $('#quizOptions').innerHTML = '<button class="primary-btn" id="againQuiz">再玩一次 →</button>'; $('#quizFeedback').textContent = state.quizScore === state.quiz.length ? '满分！你是单词岛的超级探险家！' : '做得很好，再复习一下就更棒啦！'; $('#againQuiz').addEventListener('click', startQuiz); return; } const distractors = shuffled(allWords.filter(w => w.key !== word.key)).slice(0, 3).map(w => w.chinese); const choices = shuffled([word.chinese, ...distractors]); $('#quizQuestion').textContent = `“${word.english}” 的意思是？`; $('#quizOptions').innerHTML = choices.map(choice => `<button class="quiz-option" data-answer="${choice}">${choice}</button>`).join(''); $('#quizFeedback').textContent = `第 ${state.quizStep + 1} / ${state.quiz.length} 题`; document.querySelectorAll('[data-answer]').forEach(btn => btn.addEventListener('click', () => answerQuiz(btn, word))); }
function answerQuiz(button, word) { const correct = button.dataset.answer === word.chinese; document.querySelectorAll('[data-answer]').forEach(btn => { btn.disabled = true; if (btn.dataset.answer === word.chinese) btn.classList.add('correct'); }); if (correct) { state.quizScore++; state.mastered.add(word.key); state.review.delete(word.key); button.classList.add('correct'); $('#quizFeedback').textContent = '答对啦！+1 颗小星星 ⭐'; } else { button.classList.add('wrong'); state.review.add(word.key); $('#quizFeedback').textContent = `正确答案是“${word.chinese}”，已放进复习站。`; } save(); updateProgress(); renderReview(); renderModules($('#searchInput').value); $('#quizStars').textContent = Array.from({length:5}, (_,i) => i < state.quizScore ? '★' : '☆').join(' '); setTimeout(() => { state.quizStep++; renderQuestion(); }, 1000); }

document.querySelectorAll('.tab').forEach(tab => tab.addEventListener('click', () => switchTab(tab.dataset.tab)));
$('#searchInput').addEventListener('input', e => renderModules(e.target.value));
$('#flashcard').addEventListener('click', () => { state.flipped = !state.flipped; $('#flashcard').classList.toggle('flipped', state.flipped); });
$('#speakWord').addEventListener('click', e => { e.stopPropagation(); speakCurrent(); }); $('#prevWord').addEventListener('click', () => changeCard(-1)); $('#nextWord').addEventListener('click', () => changeCard(1)); $('#needReview').addEventListener('click', () => markWord(false)); $('#knowWord').addEventListener('click', () => markWord(true));
$('#startLearning').addEventListener('click', () => chooseModule('m1')); $('#goQuiz').addEventListener('click', () => { switchTab('quiz'); startQuiz(); }); $('#startQuiz').addEventListener('click', startQuiz); $('#reviewAll').addEventListener('click', () => { const words = allWords.filter(w => state.review.has(w.key)); if (!words.length) return toast('复习站暂时没有单词哦！'); switchTab('learn'); chooseModule(words[0].module.id, words); });
$('#soundToggle').addEventListener('click', () => { state.sound = !state.sound; $('#soundToggle').textContent = state.sound ? '🔊 发音' : '🔇 静音'; toast(state.sound ? '发音已开启' : '发音已关闭'); });
document.addEventListener('keydown', e => { if (e.key === 'ArrowRight') changeCard(1); if (e.key === 'ArrowLeft') changeCard(-1); if (e.key === ' ' && document.activeElement.tagName !== 'INPUT') { e.preventDefault(); $('#flashcard').click(); } });
updateProgress(); renderModules(); renderReview();
