const modules = [
  { id: 'u1', name: 'Unit 1 · 运动与梦想', icon: '🏅', color: '#eeeaff', shade: '#ded7ff', words: [
    ['sport','运动','/spɔːt/'],['jump','跳','/dʒʌmp/'],['high','高高地','/haɪ/'],['far','远','/fɑː(r)/'],['ping-pong','乒乓球运动','/ˈpɪŋ pɒŋ/'],['volleyball','排球（运动）','/ˈvɒlibɔːl/'],['first','最初','/fɜːst/'],['at first','起初','/æt ˈfɜːst/'],['hope','希望','/həʊp/'],['lose','失去','/luːz/'],['because','因为','/bɪˈkɒz/'],['because of sb/sth','因为某人/某事物','—'],['cancer','癌（症）','/ˈkænsə(r)/'],['across','横跨','/əˈkrɒs/'],['money','钱','/ˈmʌni/'],['hard','困难的','/hɑːd/'],['kind','友善的','/kaɪnd/'],['keep','持续','/kiːp/'],['month','月','/mʌnθ/'],['ill','生病的','/ɪl/'],['year','年；年度','/jɪə(r)/'],['remember','纪念；记住','/rɪˈmembə(r)/'],['fail','失败','/feɪl/'],['give','给予','/ɡɪv/'],['give up','放弃某事','/ɡɪv ˈʌp/'],['never','决不，永不','/ˈnevə(r)/'],['try','努力；尝试','/traɪ/'],['player','运动员，选手','/ˈpleɪə(r)/'],['ability','能力','/əˈbɪləti/'] ] },
  { id: 'u2', name: 'Unit 2 · 家务小帮手', icon: '🧹', color: '#e2f8ef', shade: '#c5eedf', words: [
    ['phew','啊，唷，唉','/fjuː/'],['wash','洗','/wɒʃ/'],['dish','盘子，碟子','/dɪʃ/'],['feed','喂养，给……食物','/fiːd/'],['sweep','扫，打扫','/swiːp/'],['floor','地板，地面','/flɔː(r)/'],['rubbish','垃圾','/ˈrʌbɪʃ/'],['chore','家庭杂务','/tʃɔː(r)/'],['to-do list','待办清单','/tuː duː lɪst/'],['may','可以（表示允许）','/meɪ/'],['outside','在室外','/ˌaʊtˈsaɪd/'],['tidy','整理，收拾','/ˈtaɪdi/'],['easy','容易的','/ˈiːzi/'],['clean','清洁的，干净的','/kliːn/'],['woof','汪汪（狗吠声）','/wʊf/'],['job','任务，事情','/dʒɒb/'],['good job','干得好，真不错','/ɡʊd dʒɒb/'],['dirty','脏的','/ˈdɜːrti/'],['desk','书桌，写字台','/desk/'],['wall','墙','/wɔːl/'],['again','再一次','/əˈɡen/'],['also','除此之外，还','/ˈɔːlsoʊ/'],['problem','问题','/ˈprɒbləm/'],['finish','完成，做完','/ˈfɪnɪʃ/'],['sunshine','阳光；幸福','/ˈsʌnʃaɪn/'],['sometimes','有时','/ˈsʌmtaɪmz/'],['feel','感受到，觉得','/fiːl/'],['tired','困倦的；疲惫的，累的','/ˈtaɪərd/'],['helpful','有用的，有帮助的','/ˈhelpfl/'],['warm','（使）变暖和；温暖的','/wɔːm/'],['warm up','（使）变暖','/wɔːm ʌp/'],['water','给……浇水','/ˈwɔːtər/'],['yard','庭院','/jɑːrd/'],['helper','帮手；助手','/ˈhelpər/'],['pick','采，摘','/pɪk/'],['pig','猪','/pɪɡ/'],['cow','母牛；奶牛','/kaʊ/'],['collect','收集，采集','/kəˈlekt/'],['cut','修剪','/kʌt/'],['grass','草，青草','/ɡrɑːs/'] ] },
  { id: 'u3', name: 'Unit 3 · 天气日记', icon: '⛅', color: '#e5f7ff', shade: '#c8e8fa', words: [
    ['weather','天气','/ˈweðə(r)/'],['sunny','阳光充足的','/ˈsʌni/'],['cloud','云','/klaʊd/'],['by','经过','/baɪ/'],['cloudy','多云的，阴天的','/ˈklaʊdi/'],['wind','风','/wɪnd/'],['blow','吹，刮','/bləʊ/'],['windy','风大的；多风的','/ˈwɪndi/'],['rain','雨','/reɪn/'],['rainy','多雨的','/ˈreɪni/'],['snow','雪','/snəʊ/'],['any','任何一个','/ˈeni/'],['cold','冷的，寒冷的','/kəʊld/'],['or','或者','/ɔː(r)/'],['enjoy','享受……的乐趣','/ɪnˈdʒɔɪ/'],['diary','日记','/ˈdaɪəri/'],['special','特殊的，特别的','/ˈspeʃl/'],['teacher','老师','/ˈtiːtʃə(r)/'],['taste','有……的味道','/teɪst/'],['ice cream','冰激凌，雪糕','/ˈaɪs kriːm/'],['real','真的，真正的','/rɪəl/'],['later','之后','/ˈleɪtə(r)/'],['surprise','意想不到的事','/səˈpraɪz/'],['coat','外套','/kəʊt/'],['turn','转身，转动','/tɜːn/'],['turn on','打开','/tɜːn ˈɒn/'],['TV','电视','/ˌtiː ˈviː/'],['report','报道','/rɪˈpɔːt/'] ] },
  { id: 'u4', name: 'Unit 4 · 四季时光', icon: '🍂', color: '#fff1dc', shade: '#ffe0b2', words: [
    ['season','季节','/ˈsiːzn/'],['spring','春天，春季','/sprɪŋ/'],['summer','夏天，夏季','/ˈsʌmə(r)/'],['autumn','秋天，秋季','/ˈɔːtəm/'],['winter','冬天，冬季','/ˈwɪntə(r)/'],['favourite','最喜欢的','/ˈfeɪvərɪt/'],['birthday','生日','/ˈbɜːθdeɪ/'],['fly','放飞','/flaɪ/'],['fly kites','放风筝','/flaɪ ˈkaɪts/'],['snowstorm','雪暴，暴风雪','/ˈsnəʊstɔːm/'],['beach','海滩','/biːtʃ/'],['sea','海，海洋','/siː/'],['equator','赤道','/ɪˈkweɪtə(r)/'],['round','到处','/raʊnd/'],['quite','非常，十分','/kwaɪt/'],['join','参与，加入','/dʒɔɪn/'] ] },
  { id: 'u5', name: 'Unit 5 · 交通出行', icon: '🚆', color: '#fae8f1', shade: '#f4cde0', words: [
    ['bus','公交车，公共汽车','/bʌs/'],['car','汽车','/kɑː(r)/'],['train','火车，列车','/treɪn/'],['city','城市','/ˈsɪti/'],['town','镇，城镇','/taʊn/'],['plane','飞机','/pleɪn/'],['sky','天，天空','/skaɪ/'],['ship','大船','/ʃɪp/'],['place','地方，地点','/pleɪs/'],['near','（距离）近的','/nɪə(r)/'],['travel','旅行','/ˈtrævl/'],['way','方式，方法','/weɪ/'],['picnic','野餐','/ˈpɪknɪk/'],['minute','分钟','/ˈmɪnɪt/'],['wear','穿','/weə(r)/'],['live','住，居住','/lɪv/'],['away','离开，相距','/əˈweɪ/'],['truck','货车，卡车','/trʌk/'],['bamboo','竹，竹子','/ˌbæmˈbuː/'],['airport','机场','/ˈeəpɔːt/'],['bike','自行车','/baɪk/'],['ring','（钟、铃）鸣响','/rɪŋ/'],['beep','（使）（汽车喇叭）鸣响','/biːp/'],['subway','地铁','/ˈsʌbweɪ/'],['whoosh','（呼呼地）飞快移动','/wʊʃ/'],['tram','有轨电车','/træm/'],['chug','（汽车、火车等）突突地缓慢前进','/tʃʌɡ/'] ] },
  { id: 'u6', name: 'Unit 6 · 城市问路', icon: '🗺️', color: '#e8edff', shade: '#d2dbff', words: [
    ['wheel','车轮','/wiːl/'],['left','向左，朝左','/left/'],['straight','笔直地','/streɪt/'],['library','图书室；图书馆','/ˈlaɪbrəri/'],['centre','中心','/ˈsentər/'],['cinema','电影院','/ˈsɪnəmə/'],['hospital','医院','/ˈhɒspɪtl/'],['supermarket','超市','/ˈsuːpərmɑːrkɪt/'],['museum','博物馆，博物院','/mjuˈziːəm/'],['tomorrow','明天','/təˈmɒroʊ/'],['woman','女性，女人','/ˈwʊmən/'],['excuse','原谅','/ɪkˈskjuːz/'],['excuse me','劳驾，打扰一下，对不起','/ɪkˈskjuːz miː/'],['wish','希望，愿望','/wɪʃ/'],['true','真的，真实的','/truː/'],['step','步','/step/'],['own','自己的','/oʊn/'],['cross','横穿','/krɒs/'],['careful','谨慎的','/ˈkerfl/'],['be careful','当心，小心','/biː ˈkerfl/'],['underground','在地（面）下','/ˈʌndərɡraʊnd/'] ] }
];

const examples = {
  sport: 'Sport is good for us.', jump: 'Jump high, please!', high: 'The kite flies high.', far: 'My school is far from here.', 'ping-pong': 'I like playing ping-pong.', volleyball: 'They play volleyball after school.', first: 'I am the first one here.', 'at first': 'At first, it was hard.', hope: 'I hope you are happy.', lose: 'Do not lose your book.', because: 'I am happy because it is sunny.', 'because of sb/sth': 'We stayed home because of the rain.', cancer: 'Cancer is a serious illness.', across: 'The cat runs across the road.', money: 'I have some money.', hard: 'This question is hard.', kind: 'My teacher is kind.', keep: 'Keep your room clean.', month: 'June is a warm month.', ill: 'She is ill today.', year: 'A year has twelve months.', remember: 'Remember to do your homework.', fail: 'Try again if you fail.', give: 'Please give me the pen.', 'give up': 'Do not give up.', never: 'I never eat too much candy.', try: 'Try your best!', player: 'He is a football player.', ability: 'Everyone has an ability.',
  phew: 'Phew! That is a big box.', wash: 'Wash your hands.', dish: 'Put the dish on the table.', feed: 'I feed my fish every day.', sweep: 'Please sweep the floor.', floor: 'The ball is on the floor.', rubbish: 'Put rubbish in the bin.', chore: 'Cleaning is my chore.', 'to-do list': 'My to-do list is very long.', may: 'May I come in?', outside: 'The children are outside.', tidy: 'Please tidy your desk.', easy: 'This book is easy.', clean: 'The classroom is clean.', woof: 'Woof! The dog is happy.', job: 'This is a good job.', 'good job': 'Good job, Tom!', dirty: 'My shoes are dirty.', desk: 'My books are on the desk.', wall: 'There is a clock on the wall.', again: 'Please say it again.', also: 'I also like music.', problem: 'Can you help me with this problem?', finish: 'Finish your homework first.', sunshine: 'I like the warm sunshine.', sometimes: 'I sometimes play chess.', feel: 'I feel happy today.', tired: 'I am tired after running.', helpful: 'My friend is helpful.', warm: 'The sun is warm.', 'warm up': 'Let us warm up first.', water: 'Please water the flowers.', yard: 'The dog runs in the yard.', helper: 'My little brother is a good helper.', pick: 'Pick up your pencil.', pig: 'The pig is pink.', cow: 'The cow eats grass.', collect: 'I collect leaves in autumn.', cut: 'Cut the paper carefully.', grass: 'The sheep eats grass.',
  weather: 'What is the weather like?', sunny: 'It is sunny today.', cloud: 'Look at the white cloud.', by: 'I go to school by bus.', cloudy: 'It is cloudy this morning.', wind: 'The wind is strong.', blow: 'The wind can blow hard.', windy: 'It is windy today.', rain: 'I can hear the rain.', rainy: 'It is a rainy day.', snow: 'The snow is white.', any: 'Do you have any water?', cold: 'It is cold in winter.', or: 'Tea or milk?', enjoy: 'I enjoy this game.', diary: 'I write a diary.', special: 'Today is a special day.', teacher: 'My teacher is nice.', taste: 'The soup tastes good.', 'ice cream': 'I like chocolate ice cream.', real: 'Is this story real?', later: 'See you later.', surprise: 'What a nice surprise!', coat: 'Put on your coat.', turn: 'Turn left here.', 'turn on': 'Please turn on the TV.', TV: 'We watch TV at home.', report: 'Here is the weather report.',
  season: 'My favourite season is spring.', spring: 'Spring is warm.', summer: 'Summer is hot.', autumn: 'Autumn is cool.', winter: 'Winter is cold.', favourite: 'Blue is my favourite colour.', birthday: 'Today is my birthday.', fly: 'Birds can fly.', 'fly kites': 'We fly kites in spring.', snowstorm: 'The snowstorm is very strong.', beach: 'We play on the beach.', sea: 'The sea is blue.', equator: 'The equator is very hot.', round: 'We walk round the lake.', quite: 'It is quite nice.', join: 'Please join our game.',
  bus: 'I go to school by bus.', car: 'My dad has a car.', train: 'The train is fast.', city: 'Beijing is a big city.', town: 'My grandparents live in a town.', plane: 'The plane is in the sky.', sky: 'The sky is blue.', ship: 'The ship is on the sea.', place: 'This is a nice place.', near: 'The park is near my home.', travel: 'We travel in summer.', way: 'This is the way to school.', picnic: 'We have a picnic in the park.', minute: 'Wait a minute, please.', wear: 'I wear a red coat.', live: 'I live in Jinjiang.', away: 'The shop is far away.', truck: 'The truck is big.', bamboo: 'Pandas like bamboo.', airport: 'The plane is at the airport.', bike: 'I ride my bike.', ring: 'The bell rings at eight.', beep: 'The car goes beep beep.', subway: 'We take the subway.', whoosh: 'The train goes whoosh!', tram: 'The tram is yellow.', chug: 'The little train goes chug chug.',
  wheel: 'The bike has two wheels.', left: 'Turn left at the school.', straight: 'Go straight on.', library: 'I read books in the library.', centre: 'The shop is in the centre.', cinema: 'Let us go to the cinema.', hospital: 'The hospital is near here.', supermarket: 'Mum is at the supermarket.', museum: 'We visit the museum.', tomorrow: 'See you tomorrow.', woman: 'The woman is my aunt.', excuse: 'Please excuse me.', 'excuse me': 'Excuse me, where is the library?', wish: 'I wish you a happy day.', true: 'The story is true.', step: 'Take one step forward.', own: 'This is my own room.', cross: 'Cross the road carefully.', careful: 'Be careful with the glass.', 'be careful': 'Be careful! The floor is wet.', underground: 'The subway is underground.'
};
const allWords = modules.flatMap(module => module.words.map((word, index) => ({ module, index, english: word[0], chinese: word[1], phonetic: word[2], example: examples[word[0]] || `Say the word: ${word[0]}.`, key: `${module.id}-${index}` })));
const validKeys = new Set(allWords.map(word => word.key));
const savedMastered = JSON.parse(localStorage.getItem('wordIslandMastered') || '[]').filter(key => validKeys.has(key));
const savedReview = JSON.parse(localStorage.getItem('wordIslandReview') || '[]').filter(key => validKeys.has(key));
const state = { module: null, words: [], card: 0, flipped: false, quiz: null, quizScore: 0, quizStep: 0, sound: true, mastered: new Set(savedMastered), review: new Set(savedReview) };
const $ = selector => document.querySelector(selector);

function save() { localStorage.setItem('wordIslandMastered', JSON.stringify([...state.mastered])); localStorage.setItem('wordIslandReview', JSON.stringify([...state.review])); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 1900); }
function updateProgress() { const count = state.mastered.size; const total = allWords.length; $('#masteredCount').textContent = count; $('#wordTotal').textContent = total; $('#overallProgress').style.width = `${Math.round(count / total * 100)}%`; $('#progressLabel').textContent = count === 0 ? '刚刚启航' : count < 30 ? '正在出发' : count < 85 ? '乘风破浪' : count < total ? '单词小达人' : '全册通关！'; $('#reviewBadge').textContent = state.review.size; }
function moduleMastered(module) { return module.words.filter((_, i) => state.mastered.has(`${module.id}-${i}`)).length; }
function renderModules(filter = '') { const q = filter.trim().toLowerCase(); const shown = modules.filter(module => !q || module.name.toLowerCase().includes(q) || module.words.some(word => word[0].toLowerCase().includes(q) || word[1].includes(q))); $('#moduleGrid').innerHTML = shown.map(module => `<button class="module-card ${state.module?.id === module.id ? 'active' : ''}" data-module="${module.id}" style="--card:${module.color};--shade:${module.shade}"><span class="module-icon">${module.icon}</span><strong>${module.name}</strong><small>${module.words.length} 个词汇</small><span class="module-progress">${moduleMastered(module)}/${module.words.length}</span></button>`).join('') || '<p>没有找到这个词，再换个关键词试试。</p>'; document.querySelectorAll('[data-module]').forEach(el => el.addEventListener('click', () => chooseModule(el.dataset.module))); }
function chooseModule(id, reviewWords = null) { state.module = modules.find(module => module.id === id) || modules[0]; state.words = reviewWords || allWords.filter(word => word.module.id === state.module.id); state.card = 0; state.flipped = false; renderModules($('#searchInput').value); renderCard(); $('#learnZone').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function renderCard() { const word = state.words[state.card]; const card = $('#flashcard'); if (!word) { card.classList.add('empty'); return; } card.classList.remove('empty'); card.classList.toggle('flipped', state.flipped); $('#lessonTag').textContent = state.words.length === state.module.words.length ? state.module.name : '复习站'; $('#lessonTitle').textContent = `${state.module.icon} ${state.module.name}`; $('#lessonHint').textContent = '听发音，翻开卡片看中文，再判断自己记住了吗？'; $('#cardIndex').textContent = state.card + 1; $('#cardTotal').textContent = state.words.length; $('#wordEnglish').textContent = word.english; $('#wordChinese').textContent = word.chinese; $('#wordPhonetic').textContent = word.phonetic; $('#wordExample').textContent = word.example; }
function speakCurrent() { const word = state.words[state.card]; if (!word || !state.sound || !('speechSynthesis' in window)) return; speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(word.english); utterance.lang = 'en-US'; utterance.rate = .78; speechSynthesis.speak(utterance); }
function changeCard(direction) { if (!state.words.length) return; state.card = (state.card + direction + state.words.length) % state.words.length; state.flipped = false; renderCard(); speakCurrent(); }
function markWord(known) { const word = state.words[state.card]; if (!word) return; if (known) { state.mastered.add(word.key); state.review.delete(word.key); toast('太棒了！这个词点亮啦 ✨'); } else { state.review.add(word.key); state.mastered.delete(word.key); toast('已放进复习站，明天再见它！'); } save(); updateProgress(); renderModules($('#searchInput').value); renderReview(); if (state.card < state.words.length - 1) setTimeout(() => changeCard(1), 260); else renderCard(); }
function renderReview() { const words = allWords.filter(word => state.review.has(word.key)); $('#reviewList').innerHTML = words.length ? words.map(word => `<div class="review-word"><div><strong>${word.english}</strong><small>${word.chinese}</small></div><button data-review="${word.key}">去复习 →</button></div>`).join('') : '<div class="review-empty"><span>🧺</span>复习站还是空的。遇到不熟的词，就点“还不熟”放进来吧！</div>'; document.querySelectorAll('[data-review]').forEach(btn => btn.addEventListener('click', () => { const word = allWords.find(item => item.key === btn.dataset.review); switchTab('learn'); chooseModule(word.module.id, [word]); })); }
function switchTab(tab) { document.querySelectorAll('.tab').forEach(el => el.classList.toggle('active', el.dataset.tab === tab)); document.querySelectorAll('.panel').forEach(el => el.classList.remove('active')); $(`#${tab}Panel`).classList.add('active'); if (tab === 'review') renderReview(); }
function shuffled(items) { return [...items].sort(() => Math.random() - .5); }
function startQuiz() { const pool = state.module ? allWords.filter(word => word.module.id === state.module.id) : allWords; state.quiz = shuffled(pool).slice(0, Math.min(5, pool.length)); state.quizScore = 0; state.quizStep = 0; $('#quizStars').textContent = '☆ ☆ ☆ ☆ ☆'; renderQuestion(); }
function renderQuestion() { const word = state.quiz[state.quizStep]; if (!word) { $('#quizQuestion').textContent = `挑战完成！你答对了 ${state.quizScore} / ${state.quiz.length} 题`; $('#quizOptions').innerHTML = '<button class="primary-btn" id="againQuiz">再玩一次 →</button>'; $('#quizFeedback').textContent = state.quizScore === state.quiz.length ? '满分！你是单词岛的超级探险家！' : '做得很好，再复习一下就更棒啦！'; $('#againQuiz').addEventListener('click', startQuiz); return; } const distractors = shuffled(allWords.filter(item => item.key !== word.key)).slice(0, 3).map(item => item.chinese); const choices = shuffled([word.chinese, ...distractors]); $('#quizQuestion').textContent = `“${word.english}” 的意思是？`; $('#quizOptions').innerHTML = choices.map(choice => `<button class="quiz-option" data-answer="${choice}">${choice}</button>`).join(''); $('#quizFeedback').textContent = `第 ${state.quizStep + 1} / ${state.quiz.length} 题`; document.querySelectorAll('[data-answer]').forEach(btn => btn.addEventListener('click', () => answerQuiz(btn, word))); }
function answerQuiz(button, word) { const correct = button.dataset.answer === word.chinese; document.querySelectorAll('[data-answer]').forEach(btn => { btn.disabled = true; if (btn.dataset.answer === word.chinese) btn.classList.add('correct'); }); if (correct) { state.quizScore++; state.mastered.add(word.key); state.review.delete(word.key); $('#quizFeedback').textContent = '答对啦！+1 颗小星星 ⭐'; } else { button.classList.add('wrong'); state.review.add(word.key); $('#quizFeedback').textContent = `正确答案是“${word.chinese}”，已放进复习站。`; } save(); updateProgress(); renderReview(); renderModules($('#searchInput').value); $('#quizStars').textContent = Array.from({ length: 5 }, (_, i) => i < state.quizScore ? '★' : '☆').join(' '); setTimeout(() => { state.quizStep++; renderQuestion(); }, 1000); }

document.querySelectorAll('.tab').forEach(tab => tab.addEventListener('click', () => switchTab(tab.dataset.tab)));
$('#searchInput').addEventListener('input', e => renderModules(e.target.value));
$('#flashcard').addEventListener('click', () => { state.flipped = !state.flipped; $('#flashcard').classList.toggle('flipped', state.flipped); });
$('#speakWord').addEventListener('click', e => { e.stopPropagation(); speakCurrent(); }); $('#prevWord').addEventListener('click', () => changeCard(-1)); $('#nextWord').addEventListener('click', () => changeCard(1)); $('#needReview').addEventListener('click', () => markWord(false)); $('#knowWord').addEventListener('click', () => markWord(true));
$('#startLearning').addEventListener('click', () => chooseModule('u1')); $('#goQuiz').addEventListener('click', () => { switchTab('quiz'); startQuiz(); }); $('#startQuiz').addEventListener('click', startQuiz); $('#reviewAll').addEventListener('click', () => { const words = allWords.filter(word => state.review.has(word.key)); if (!words.length) return toast('复习站暂时没有单词哦！'); switchTab('learn'); chooseModule(words[0].module.id, words); });
$('#soundToggle').addEventListener('click', () => { state.sound = !state.sound; $('#soundToggle').textContent = state.sound ? '🔊 发音' : '🔇 静音'; toast(state.sound ? '发音已开启' : '发音已关闭'); });
document.addEventListener('keydown', e => { if (e.key === 'ArrowRight') changeCard(1); if (e.key === 'ArrowLeft') changeCard(-1); if (e.key === ' ' && document.activeElement.tagName !== 'INPUT') { e.preventDefault(); $('#flashcard').click(); } });
updateProgress(); renderModules(); renderReview();
