const upperModules = [
  { id: 'u1', name: 'Unit 1 · 运动与梦想', icon: '🏅', color: '#eeeaff', shade: '#ded7ff', words: [
    ['sport','运动','/spɔːt/'],['jump','跳','/dʒʌmp/'],['high','高高地','/haɪ/'],['far','远','/fɑː(r)/'],['ping-pong','乒乓球运动','/ˈpɪŋ pɒŋ/'],['volleyball','排球（运动）','/ˈvɒlibɔːl/'],['first','最初','/fɜːst/'],['at first','起初','/æt ˈfɜːst/'],['hope','希望','/həʊp/'],['lose','失去','/luːz/'],['because','因为','/bɪˈkɒz/'],['because of sb/sth','因为某人/某事物','—'],['cancer','癌（症）','/ˈkænsə(r)/'],['across','横跨','/əˈkrɒs/'],['money','钱','/ˈmʌni/'],['hard','困难的','/hɑːd/'],['kind','友善的','/kaɪnd/'],['keep','持续','/kiːp/'],['month','月','/mʌnθ/'],['ill','生病的','/ɪl/'],['year','年；年度','/jɪə(r)/'],['remember','纪念；记住','/rɪˈmembə(r)/'],['fail','失败','/feɪl/'],['give','给予','/ɡɪv/'],['give up','放弃某事','/ɡɪv ˈʌp/'],['never','决不，永不','/ˈnevə(r)/'],['try','努力；尝试','/traɪ/'],['player','运动员，选手','/ˈpleɪə(r)/'],['ability','能力','/əˈbɪləti/'] ] },
  { id: 'u2', name: 'Unit 2 · 家务小帮手', icon: '🧹', color: '#e2f8ef', shade: '#c5eedf', words: [
    ['phew','啊，唷，唉','/fjuː/'],['wash','洗','/wɒʃ/'],['dish','盘子，碟子','/dɪʃ/'],['feed','喂养，给……食物','/fiːd/'],['sweep','扫，打扫','/swiːp/'],['floor','地板，地面','/flɔː(r)/'],['rubbish','垃圾','/ˈrʌbɪʃ/'],['chore','家庭杂务','/tʃɔː(r)/'],['to-do list','待办清单','/tuː duː lɪst/'],['may','可以（表示允许）','/meɪ/'],['outside','在室外','/ˌaʊtˈsaɪd/'],['tidy','整理，收拾','/ˈtaɪdi/'],['easy','容易的','/ˈiːzi/'],['clean','清洁的，干净的','/kliːn/'],['woof','汪汪（狗吠声）','/wʊf/'],['job','任务，事情','/dʒɒb/'],['good job','干得好，真不错','/ɡʊd dʒɒb/'],['dirty','脏的','/ˈdɜːrti/'],['desk','书桌，写字台','/desk/'],['wall','墙','/wɔːl/'],['again','再一次','/əˈɡen/'],['also','除此之外，还','/ˈɔːlsoʊ/'],['problem','问题','/ˈprɒbləm/'],['finish','完成，做完','/ˈfɪnɪʃ/'],['sunshine','阳光；幸福','/ˈsʌnʃaɪn/'],['sometimes','有时','/ˈsʌmtaɪmz/'],['feel','感受到，觉得','/fiːl/'],['tired','困倦的；疲惫的，累的','/ˈtaɪərd/'],['helpful','有用的，有帮助的','/ˈhelpfl/'],['warm','（使）变暖和；温暖的','/wɔːm/'],['warm up','（使）变暖','/wɔːm ʌp/'],['water','给……浇水','/ˈwɔːtər/'],['yard','庭院','/jɑːrd/'],['helper','帮手；助手','/ˈhelpər/'],['pick','采，摘','/pɪk/'],['pig','猪','/pɪɡ/'],['cow','母牛；奶牛','/kaʊ/'],['collect','收集，采集','/kəˈlekt/'],['cut','修剪','/kʌt/'],['grass','草，青草','/ɡrɑːs/'] ] },
  { id: 'u3', name: 'Unit 3 · 天气日记', icon: '⛅', color: '#e5f7ff', shade: '#c8e8fa', words: [
    ['weather','天气','/ˈweðə(r)/'],['sunny','阳光充足的','/ˈsʌni/'],['cloud','云','/klaʊd/'],['by','经过','/baɪ/'],['cloudy','多云的，阴天的','/ˈklaʊdi/'],['wind','风','/wɪnd/'],['blow','吹，刮','/bləʊ/'],['windy','风大的；多风的','/ˈwɪndi/'],['rain','雨','/reɪn/'],['rainy','多雨的','/ˈreɪni/'],['snow','雪','/snəʊ/'],['any','任何一个','/ˈeni/'],['cold','冷的，寒冷的','/kəʊld/'],['or','或者','/ɔː(r)/'],['enjoy','享受……的乐趣','/ɪnˈdʒɔɪ/'],['diary','日记','/ˈdaɪəri/'],['special','特殊的，特别的','/ˈspeʃl/'],['teacher','老师','/ˈtiːtʃə(r)/'],['taste','有……的味道','/teɪst/'],['ice cream','冰激凌，雪糕','/ˈaɪs kriːm/'],['real','真的，真正的','/rɪəl/'],['later','之后','/ˈleɪtə(r)/'],['surprise','意想不到的事','/səˈpraɪz/'],['coat','外套','/kəʊt/'],['turn','转身，转动','/tɜːn/'],['turn on','打开','/tɜːn ˈɒn/'],['TV','电视','/ˌtiː ˈviː/'],['report','报道','/rɪˈpɔːt/'] ] },
  { id: 'u4', name: 'Unit 4 · 四季时光', icon: '🍂', color: '#fff1dc', shade: '#ffe0b2', words: [
    ['season','季节','/ˈsiːzn/'],['spring','春天，春季','/sprɪŋ/'],['summer','夏天，夏季','/ˈsʌmə(r)/'],['autumn','秋天，秋季','/ˈɔːtəm/'],['winter','冬天，冬季','/ˈwɪntə(r)/'],['favourite','最喜欢的','/ˈfeɪvərɪt/'],['birthday','生日','/ˈbɜːθdeɪ/'],['fly','放飞','/flaɪ/'],['fly kites','放风筝','/flaɪ ˈkaɪts/'],['snowstorm','雪暴，暴风雪','/ˈsnəʊstɔːm/'],['beach','海滩','/biːtʃ/'],['sea','海，海洋','/siː/'],['equator','赤道','/ɪˈkweɪtə(r)/'],['round','到处','/raʊnd/'],['quite','非常，十分','/kwaɪt/'],['join','参与，加入','/dʒɔɪn/'] ] },
  { id: 'u5', name: 'Unit 5 · 交通出行', icon: '🚆', color: '#fae8f1', shade: '#f4cde0', words: [
    ['bus','公交车，公共汽车','/bʌs/'],['car','汽车','/kɑː(r)/'],['train','火车，列车','/treɪn/'],['city','城市','/ˈsɪti/'],['town','镇，城镇','/taʊn/'],['plane','飞机','/pleɪn/'],['sky','天，天空','/skaɪ/'],['ship','大船','/ʃɪp/'],['place','地方，地点','/pleɪs/'],['near','（距离）近的','/nɪə(r)/'],['travel','旅行','/ˈtrævl/'],['way','方式，方法','/weɪ/'],['picnic','野餐','/ˈpɪknɪk/'],['minute','分钟','/ˈmɪnɪt/'],['wear','穿','/weə(r)/'],['live','住，居住','/lɪv/'],['away','离开，相距','/əˈweɪ/'],['truck','货车，卡车','/trʌk/'],['bamboo','竹，竹子','/ˌbæmˈbuː/'],['airport','机场','/ˈeəpɔːt/'],['bike','自行车','/baɪk/'],['ring','（钟、铃）鸣响','/rɪŋ/'],['beep','（使）（汽车喇叭）鸣响','/biːp/'],['subway','地铁','/ˈsʌbweɪ/'],['whoosh','（呼呼地）飞快移动','/wʊʃ/'],['tram','有轨电车','/træm/'],['chug','（汽车、火车等）突突地缓慢前进','/tʃʌɡ/'] ] },
  { id: 'u6', name: 'Unit 6 · 城市问路', icon: '🗺️', color: '#e8edff', shade: '#d2dbff', words: [
    ['wheel','车轮','/wiːl/'],['left','向左，朝左','/left/'],['straight','笔直地','/streɪt/'],['library','图书室；图书馆','/ˈlaɪbrəri/'],['centre','中心','/ˈsentər/'],['cinema','电影院','/ˈsɪnəmə/'],['hospital','医院','/ˈhɒspɪtl/'],['supermarket','超市','/ˈsuːpərmɑːrkɪt/'],['museum','博物馆，博物院','/mjuˈziːəm/'],['tomorrow','明天','/təˈmɒroʊ/'],['woman','女性，女人','/ˈwʊmən/'],['excuse','原谅','/ɪkˈskjuːz/'],['excuse me','劳驾，打扰一下，对不起','/ɪkˈskjuːz miː/'],['wish','希望，愿望','/wɪʃ/'],['true','真的，真实的','/truː/'],['step','步','/step/'],['own','自己的','/oʊn/'],['cross','横穿','/krɒs/'],['careful','谨慎的','/ˈkerfl/'],['be careful','当心，小心','/biː ˈkerfl/'],['underground','在地（面）下','/ˈʌndərɡraʊnd/'] ] }
];

const lowerModules = [
  { id: 'l1', name: 'Unit 1 · 职业与家人', icon: '👩‍⚕️', color: '#e2f8ef', shade: '#c5eedf', words: [
    ['doctor','医生，大夫','/ˈdɒktə(r)/'],['fireman','消防队员','/ˈfaɪəmən/'],['farmer','农民','/ˈfɑːmə(r)/'],['cook','厨师，炊事员','/kʊk/'],['police','警察','/pəˈliːs/'],['police officer','警察，警官','/pəˈliːs ˈɒfɪsə(r)/'],['station','所；站；台；局','/ˈsteɪʃn/'],['police station','警察局，派出所','/pəˈliːs ˈsteɪʃn/'],['fire','火','/ˈfaɪə(r)/'],['fire station','消防站','/ˈfaɪə(r) ˈsteɪʃn/'],['restaurant','饭店','/ˈrestərɒnt/'],['father','父亲，爸爸','/ˈfɑːðə(r)/'],['field','田地，田野','/fiːld/'],['painter','画家','/ˈpeɪntə(r)/'],['use','用，使用','/juːz/'],['brush','刷子；画笔','/brʌʃ/'],['scientist','科学家','/ˈsaɪəntɪst/'],['writer','作家','/ˈraɪtə(r)/'],['worker','技术工人','/ˈwɜːkə(r)/'],['aunt','姑母，姨母','/ɑːnt/'],['night','夜间，夜晚','/naɪt/'],['owl','猫头鹰','/aʊl/'],['night owl','夜猫子，喜欢熬夜的人','/naɪt aʊl/'],['driver','司机，驾驶员','/ˈdraɪvə(r)/'],['taxi','出租车，计程车','/ˈtæksi/'],['safe','安全的；平安无事的','/seɪf/'],['nurse','护士','/nɜːs/'],['brighten','使更明亮','/ˈbraɪtn/'],['uncle','叔叔，伯伯','/ˈʌŋkl/'],['bake','烘，烤，焙','/beɪk/'],['bee','蜜蜂','/biː/'],['postman','邮递员','/ˈpəʊstmən/'],['poor','贫穷的，贫困的','/pɔː(r)/'],['bring','带来；拿来','/brɪŋ/'],['letter','信，函','/ˈletə(r)/'],['mountain','高山','/ˈmaʊntən/'] ] },
  { id: 'l2', name: 'Unit 2 · 我的心情', icon: '😊', color: '#fff1dc', shade: '#ffe0b2', words: [
    ['laugh','发出笑声，（大）笑','/lɑːf/'],['sad','不愉快的，伤心的，难过的','/sæd/'],['cry','哭，哭泣','/kraɪ/'],['angry','发怒的，生气的','/ˈæŋɡri/'],['frown','皱眉','/fraʊn/'],['scared','害怕的，恐惧的；紧张的','/skeəd/'],['shake','发抖，颤抖','/ʃeɪk/'],['excited','兴奋的，激动的','/ɪkˈsaɪtɪd/'],['opera','歌剧；歌剧艺术','/ˈɒprə/'],['next','（时间）紧接着的；下次的','/nekst/'],['cough','咳嗽，咳','/kɒf/'],['better','（健康状况）好转的','/ˈbetə(r)/'],['practise','练习，实践，实习','/ˈpræktɪs/'],['gift','礼物','/ɡɪft/'],['surprised','吃惊的，惊奇的','/səˈpraɪzd/'],['model','（尤指可拼装的）模型','/ˈmɒdl/'],['bang','砰，啪','/bæŋ/'],['shout','大声说，喊叫，呼喊','/ʃaʊt/'],['should','应当，应该','/ʃʊd/'],['break','使破裂，使破碎；使断裂','/breɪk/'],['feeling','感觉，感触','/ˈfiːlɪŋ/'],['huge','巨大的','/hjuːdʒ/'],['worried','担心的，焦虑的','/ˈwʌrid/'],['street','大街，街道','/striːt/'],['hit','撞击，碰撞','/hɪt/'] ] },
  { id: 'l3', name: 'Unit 3 · 才艺舞台', icon: '🎭', color: '#fae8f1', shade: '#f4cde0', words: [
    ['talent','天资，天赋，才能','/ˈtælənt/'],['act','演出；扮演','/ækt/'],['magic','魔术，戏法','/ˈmædʒɪk/'],['shine','表现突出，出众','/ʃaɪn/'],['puzzle','拼图游戏','/ˈpʌzl/'],['dancer','舞蹈演员','/ˈdɑːnsə(r)/'],['win','获胜，赢','/wɪn/'],['just','就，只是','/dʒʌst/'],['duck','鸭','/dʌk/'],['boy','男孩；儿子','/bɔɪ/'],['anything','任何事情，无论何事','/ˈeniθɪŋ/'],['cock-a-doodle-doo','（公鸡啼叫的）喔喔声','/ˌkɒkəˈduːdl duː/'],['enough','足够（的）','/ɪˈnʌf/'],['slowly','缓慢地，慢慢地','/ˈsləʊli/'] ] },
  { id: 'l4', name: 'Unit 4 · 植物成长', icon: '🌻', color: '#fff5cf', shade: '#f8e5a0', words: [
    ['life','一生，生活','/laɪf/'],['seed','种子，籽','/siːd/'],['earth','泥土，土壤','/ɜːθ/'],['root','根','/ruːt/'],['stem','（植物的）茎，梗，柄','/stem/'],['thin','细的','/θɪn/'],['leaf','叶，叶子','/liːf/'],['dig','挖，掘','/dɪɡ/'],['sunflower','向日葵','/ˈsʌnflaʊə(r)/'],['wheat','小麦','/wiːt/'],['cotton','棉花，棉株','/ˈkɒtn/'],['sleep','睡，睡觉','/sliːp/'],['mouse','老鼠','/maʊs/'],['grain','谷粒','/ɡreɪn/'],['miss','想念，思念，怀念（某人）','/mɪs/'],['will','将，会，要','/wɪl/'],['everything','每件事物；所有事物','/ˈevriθɪŋ/'],['cabbage','卷心菜，洋白菜，甘蓝','/ˈkæbɪdʒ/'],['paper','纸','/ˈpeɪpə(r)/'] ] },
  { id: 'l5', name: 'Unit 5 · 自然与活动', icon: '🎪', color: '#e5f7ff', shade: '#c8e8fa', words: [
    ['event','活动，事件','/ɪˈvent/'],['drama','戏剧','/ˈdrɑːmə/'],['trip','旅游；旅行，出行','/trɪp/'],['fair','户外游艺会；义卖会；集市','/feə(r)/'],['festival','节，节庆，汇演','/ˈfestɪvl/'],['horn','角','/hɔːn/'],['dot','点，小圆点','/dɒt/'],['raindrop','雨点，雨滴','/ˈreɪndrɒp/'],['more','更多的','/mɔː(r)/'],['write','书写；写字','/raɪt/'],['those','那些','/ðəʊz/'],['forest','森林，林区','/ˈfɒrɪst/'],['nature','大自然','/ˈneɪtʃə(r)/'],['hunt','搜寻，寻找','/hʌnt/'],['keeper','看守人，保管人','/ˈkiːpə(r)/'],['lovely','美好的；令人愉快的；可爱的','/ˈlʌvli/'],['student','学生','/ˈstjuːdnt/'],['fall','落下，降落，跌落','/fɔːl/'],['off','不在（某物）上面；从……上移开','/ɒf/'],['fall off','（从某物上）掉下，脱落','/fɔːl ɒf/'],['hour','小时','/ˈaʊə(r)/'],['culture','文化','/ˈkʌltʃə(r)/'],['note','笔记，记录','/nəʊt/'],['vote','选票','/vəʊt/'] ] },
  { id: 'l6', name: 'Unit 6 · 服装与故事', icon: '👕', color: '#e8edff', shade: '#d2dbff', words: [
    ['T-shirt','T 恤（衫）','/ˈtiː ʃɜːt/'],['skirt','半身裙，裙子','/skɜːt/'],['shorts','短裤','/ʃɔːts/'],['shirt','衬衫','/ʃɜːt/'],['trousers','裤子','/ˈtraʊzəz/'],['scarf','围巾','/skɑːf/'],['sweater','毛线衣，羊毛衫，针织衫','/ˈswetə(r)/'],['party','聚会，宴会','/ˈpɑːti/'],['dress','连衣裙','/dres/'],['end','最后部分，末尾','/end/'],['dressmaker','裁缝','/ˈdresmeɪkə(r)/'],['Christmas','圣诞节','/ˈkrɪsməs/'],['same','完全相同的，一模一样的','/seɪm/'],['the same','同样','/ðə seɪm/'],['wrong','不正确的，错误的','/rɒŋ/'],['clever','聪明的','/ˈklevə(r)/'],['Mr','先生','/ˈmɪstə(r)/'],['present','礼物','/ˈpreznt/'],['whale','鲸','/weɪl/'],['uniform','制服','/ˈjuːnɪfɔːm/'],['robe','长袍','/rəʊb/'],['market','市场','/ˈmɑːkɪt/'],['himself','他自己','/hɪmˈself/'],['rest','休息（时间）','/rest/'],['wave','挥手，招手','/weɪv/'],['stamp','跺（脚）；用力踩','/stæmp/'],['throw','投，扔，抛，掷','/θrəʊ/'],['ground','地，地面','/ɡraʊnd/'],['emperor','皇帝','/ˈempərə(r)/'],['musician','乐师','/mjuˈzɪʃn/'],['wife','妻子','/waɪf/'],['sound','声，声音','/saʊnd/'],['nobody','没有人，无人；谁也不','/ˈnəʊbədi/'],['pass away','过世，离世','/pɑːs əˈweɪ/'],['become','变成','/bɪˈkʌm/'],['jacket','夹克，短上衣','/ˈdʒækɪt/'],['ugly','丑陋的，难看的','/ˈʌɡli/'],['servant','（尤指旧时的）仆人，佣人','/ˈsɜːvənt/'],['Your Majesty','陛下（对国王或女王的称呼）','/jɔː ˈmædʒɪsti/'],['loudly','响亮地，大声地','/ˈlaʊdli/'] ] }
];
const termCatalog = { upper: { label: '四年级上册', modules: upperModules }, lower: { label: '四年级下册', modules: lowerModules } };
let currentTerm = localStorage.getItem('wordIslandTerm') || 'upper';
let modules = termCatalog[currentTerm].modules;

const examples = {
  sport: 'Sport is good for us.', jump: 'Jump high, please!', high: 'The kite flies high.', far: 'My school is far from here.', 'ping-pong': 'I like playing ping-pong.', volleyball: 'They play volleyball after school.', first: 'I am the first one here.', 'at first': 'At first, it was hard.', hope: 'I hope you are happy.', lose: 'Do not lose your book.', because: 'I am happy because it is sunny.', 'because of sb/sth': 'We stayed home because of the rain.', cancer: 'Cancer is a serious illness.', across: 'The cat runs across the road.', money: 'I have some money.', hard: 'This question is hard.', kind: 'My teacher is kind.', keep: 'Keep your room clean.', month: 'June is a warm month.', ill: 'She is ill today.', year: 'A year has twelve months.', remember: 'Remember to do your homework.', fail: 'Try again if you fail.', give: 'Please give me the pen.', 'give up': 'Do not give up.', never: 'I never eat too much candy.', try: 'Try your best!', player: 'He is a football player.', ability: 'Everyone has an ability.',
  phew: 'Phew! That is a big box.', wash: 'Wash your hands.', dish: 'Put the dish on the table.', feed: 'I feed my fish every day.', sweep: 'Please sweep the floor.', floor: 'The ball is on the floor.', rubbish: 'Put rubbish in the bin.', chore: 'Cleaning is my chore.', 'to-do list': 'My to-do list is very long.', may: 'May I come in?', outside: 'The children are outside.', tidy: 'Please tidy your desk.', easy: 'This book is easy.', clean: 'The classroom is clean.', woof: 'Woof! The dog is happy.', job: 'This is a good job.', 'good job': 'Good job, Tom!', dirty: 'My shoes are dirty.', desk: 'My books are on the desk.', wall: 'There is a clock on the wall.', again: 'Please say it again.', also: 'I also like music.', problem: 'Can you help me with this problem?', finish: 'Finish your homework first.', sunshine: 'I like the warm sunshine.', sometimes: 'I sometimes play chess.', feel: 'I feel happy today.', tired: 'I am tired after running.', helpful: 'My friend is helpful.', warm: 'The sun is warm.', 'warm up': 'Let us warm up first.', water: 'Please water the flowers.', yard: 'The dog runs in the yard.', helper: 'My little brother is a good helper.', pick: 'Pick up your pencil.', pig: 'The pig is pink.', cow: 'The cow eats grass.', collect: 'I collect leaves in autumn.', cut: 'Cut the paper carefully.', grass: 'The sheep eats grass.',
  weather: 'What is the weather like?', sunny: 'It is sunny today.', cloud: 'Look at the white cloud.', by: 'I go to school by bus.', cloudy: 'It is cloudy this morning.', wind: 'The wind is strong.', blow: 'The wind can blow hard.', windy: 'It is windy today.', rain: 'I can hear the rain.', rainy: 'It is a rainy day.', snow: 'The snow is white.', any: 'Do you have any water?', cold: 'It is cold in winter.', or: 'Tea or milk?', enjoy: 'I enjoy this game.', diary: 'I write a diary.', special: 'Today is a special day.', teacher: 'My teacher is nice.', taste: 'The soup tastes good.', 'ice cream': 'I like chocolate ice cream.', real: 'Is this story real?', later: 'See you later.', surprise: 'What a nice surprise!', coat: 'Put on your coat.', turn: 'Turn left here.', 'turn on': 'Please turn on the TV.', TV: 'We watch TV at home.', report: 'Here is the weather report.',
  season: 'My favourite season is spring.', spring: 'Spring is warm.', summer: 'Summer is hot.', autumn: 'Autumn is cool.', winter: 'Winter is cold.', favourite: 'Blue is my favourite colour.', birthday: 'Today is my birthday.', fly: 'Birds can fly.', 'fly kites': 'We fly kites in spring.', snowstorm: 'The snowstorm is very strong.', beach: 'We play on the beach.', sea: 'The sea is blue.', equator: 'The equator is very hot.', round: 'We walk round the lake.', quite: 'It is quite nice.', join: 'Please join our game.',
  bus: 'I go to school by bus.', car: 'My dad has a car.', train: 'The train is fast.', city: 'Beijing is a big city.', town: 'My grandparents live in a town.', plane: 'The plane is in the sky.', sky: 'The sky is blue.', ship: 'The ship is on the sea.', place: 'This is a nice place.', near: 'The park is near my home.', travel: 'We travel in summer.', way: 'This is the way to school.', picnic: 'We have a picnic in the park.', minute: 'Wait a minute, please.', wear: 'I wear a red coat.', live: 'I live in Jinjiang.', away: 'The shop is far away.', truck: 'The truck is big.', bamboo: 'Pandas like bamboo.', airport: 'The plane is at the airport.', bike: 'I ride my bike.', ring: 'The bell rings at eight.', beep: 'The car goes beep beep.', subway: 'We take the subway.', whoosh: 'The train goes whoosh!', tram: 'The tram is yellow.', chug: 'The little train goes chug chug.',
  wheel: 'The bike has two wheels.', left: 'Turn left at the school.', straight: 'Go straight on.', library: 'I read books in the library.', centre: 'The shop is in the centre.', cinema: 'Let us go to the cinema.', hospital: 'The hospital is near here.', supermarket: 'Mum is at the supermarket.', museum: 'We visit the museum.', tomorrow: 'See you tomorrow.', woman: 'The woman is my aunt.', excuse: 'Please excuse me.', 'excuse me': 'Excuse me, where is the library?', wish: 'I wish you a happy day.', true: 'The story is true.', step: 'Take one step forward.', own: 'This is my own room.', cross: 'Cross the road carefully.', careful: 'Be careful with the glass.', 'be careful': 'Be careful! The floor is wet.', underground: 'The subway is underground.'
};
const allModules = [...upperModules.map(module => ({ ...module, term: 'upper' })), ...lowerModules.map(module => ({ ...module, term: 'lower' }))];
const allWords = allModules.flatMap(module => module.words.map((word, index) => ({ module, index, english: word[0], chinese: word[1], phonetic: word[2], example: examples[word[0]] || `Listen and repeat: ${word[0]}.`, key: `${module.id}-${index}` })));
const activeWords = () => allWords.filter(word => word.module.term === currentTerm);
const validKeys = new Set(allWords.map(word => word.key));
const savedMastered = JSON.parse(localStorage.getItem('wordIslandMastered') || '[]').filter(key => validKeys.has(key));
const savedReview = JSON.parse(localStorage.getItem('wordIslandReview') || '[]').filter(key => validKeys.has(key));
const state = { module: null, words: [], card: 0, flipped: false, quiz: null, quizScore: 0, quizStep: 0, sound: true, mastered: new Set(savedMastered), review: new Set(savedReview) };
const $ = selector => document.querySelector(selector);

function save() { localStorage.setItem('wordIslandMastered', JSON.stringify([...state.mastered])); localStorage.setItem('wordIslandReview', JSON.stringify([...state.review])); }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 1900); }
function updateProgress() { const words = activeWords(); const count = words.filter(word => state.mastered.has(word.key)).length; const total = words.length; const reviewCount = words.filter(word => state.review.has(word.key)).length; $('#masteredCount').textContent = count; $('#wordTotal').textContent = total; $('#overallProgress').style.width = `${Math.round(count / total * 100)}%`; $('#progressLabel').textContent = count === 0 ? '刚刚启航' : count < 30 ? '正在出发' : count < Math.ceil(total / 2) ? '乘风破浪' : count < total ? '单词小达人' : '全册通关！'; $('#reviewBadge').textContent = reviewCount; }
function moduleMastered(module) { return module.words.filter((_, i) => state.mastered.has(`${module.id}-${i}`)).length; }
function renderModules(filter = '') { const q = filter.trim().toLowerCase(); const shown = modules.filter(module => !q || module.name.toLowerCase().includes(q) || module.words.some(word => word[0].toLowerCase().includes(q) || word[1].includes(q))); $('#moduleGrid').innerHTML = shown.map(module => `<button class="module-card ${state.module?.id === module.id ? 'active' : ''}" data-module="${module.id}" style="--card:${module.color};--shade:${module.shade}"><span class="module-icon">${module.icon}</span><strong>${module.name}</strong><small>${module.words.length} 个词汇</small><span class="module-progress">${moduleMastered(module)}/${module.words.length}</span></button>`).join('') || '<p>没有找到这个词，再换个关键词试试。</p>'; document.querySelectorAll('[data-module]').forEach(el => el.addEventListener('click', () => chooseModule(el.dataset.module))); }
function chooseModule(id, reviewWords = null) { state.module = modules.find(module => module.id === id) || modules[0]; state.words = reviewWords || allWords.filter(word => word.module.id === state.module.id); state.card = 0; state.flipped = false; renderModules($('#searchInput').value); renderCard(); $('#learnZone').scrollIntoView({ behavior: 'smooth', block: 'center' }); }
function renderCard() { const word = state.words[state.card]; const card = $('#flashcard'); if (!word) { card.classList.add('empty'); return; } card.classList.remove('empty'); card.classList.toggle('flipped', state.flipped); $('#lessonTag').textContent = state.words.length === state.module.words.length ? state.module.name : '复习站'; $('#lessonTitle').textContent = `${state.module.icon} ${state.module.name}`; $('#lessonHint').textContent = '听发音，翻开卡片看中文，再判断自己记住了吗？'; $('#cardIndex').textContent = state.card + 1; $('#cardTotal').textContent = state.words.length; $('#wordEnglish').textContent = word.english; $('#wordChinese').textContent = word.chinese; $('#wordPhonetic').textContent = word.phonetic; $('#wordExample').textContent = word.example; }
function speakCurrent() { const word = state.words[state.card]; if (!word || !state.sound || !('speechSynthesis' in window)) return; speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(word.english); utterance.lang = 'en-US'; utterance.rate = .78; speechSynthesis.speak(utterance); }
function changeCard(direction) { if (!state.words.length) return; state.card = (state.card + direction + state.words.length) % state.words.length; state.flipped = false; renderCard(); speakCurrent(); }
function markWord(known) { const word = state.words[state.card]; if (!word) return; if (known) { state.mastered.add(word.key); state.review.delete(word.key); toast('太棒了！这个词点亮啦 ✨'); } else { state.review.add(word.key); state.mastered.delete(word.key); toast('已放进复习站，明天再见它！'); } save(); updateProgress(); renderModules($('#searchInput').value); renderReview(); if (state.card < state.words.length - 1) setTimeout(() => changeCard(1), 260); else renderCard(); }
function renderReview() { const words = activeWords().filter(word => state.review.has(word.key)); $('#reviewList').innerHTML = words.length ? words.map(word => `<div class="review-word"><div><strong>${word.english}</strong><small>${word.chinese}</small></div><button data-review="${word.key}">去复习 →</button></div>`).join('') : '<div class="review-empty"><span>🧺</span>复习站还是空的。遇到不熟的词，就点“还不熟”放进来吧！</div>'; document.querySelectorAll('[data-review]').forEach(btn => btn.addEventListener('click', () => { const word = allWords.find(item => item.key === btn.dataset.review); switchTerm(word.module.term, false); switchTab('learn'); chooseModule(word.module.id, [word]); })); }
function switchTerm(term, scroll = true) { currentTerm = term; localStorage.setItem('wordIslandTerm', term); modules = termCatalog[term].modules; state.module = null; state.words = []; state.card = 0; state.flipped = false; $('#termLabel').textContent = `福建省晋江市 · 外研版（三起）${termCatalog[term].label}`; document.querySelectorAll('[data-term]').forEach(button => button.classList.toggle('active', button.dataset.term === term)); updateProgress(); renderModules(); renderReview(); renderCard(); if (scroll) $('#learnPanel').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function switchTab(tab) { document.querySelectorAll('.tab').forEach(el => el.classList.toggle('active', el.dataset.tab === tab)); document.querySelectorAll('.panel').forEach(el => el.classList.remove('active')); $(`#${tab}Panel`).classList.add('active'); if (tab === 'review') renderReview(); }
function shuffled(items) { return [...items].sort(() => Math.random() - .5); }
function startQuiz() { const pool = state.module ? allWords.filter(word => word.module.id === state.module.id) : activeWords(); state.quiz = shuffled(pool).slice(0, Math.min(5, pool.length)); state.quizScore = 0; state.quizStep = 0; $('#quizStars').textContent = '☆ ☆ ☆ ☆ ☆'; renderQuestion(); }
function renderQuestion() { const word = state.quiz[state.quizStep]; if (!word) { $('#quizQuestion').textContent = `挑战完成！你答对了 ${state.quizScore} / ${state.quiz.length} 题`; $('#quizOptions').innerHTML = '<button class="primary-btn" id="againQuiz">再玩一次 →</button>'; $('#quizFeedback').textContent = state.quizScore === state.quiz.length ? '满分！你是单词岛的超级探险家！' : '做得很好，再复习一下就更棒啦！'; $('#againQuiz').addEventListener('click', startQuiz); return; } const distractors = shuffled(allWords.filter(item => item.key !== word.key)).slice(0, 3).map(item => item.chinese); const choices = shuffled([word.chinese, ...distractors]); $('#quizQuestion').textContent = `“${word.english}” 的意思是？`; $('#quizOptions').innerHTML = choices.map(choice => `<button class="quiz-option" data-answer="${choice}">${choice}</button>`).join(''); $('#quizFeedback').textContent = `第 ${state.quizStep + 1} / ${state.quiz.length} 题`; document.querySelectorAll('[data-answer]').forEach(btn => btn.addEventListener('click', () => answerQuiz(btn, word))); }
function answerQuiz(button, word) { const correct = button.dataset.answer === word.chinese; document.querySelectorAll('[data-answer]').forEach(btn => { btn.disabled = true; if (btn.dataset.answer === word.chinese) btn.classList.add('correct'); }); if (correct) { state.quizScore++; state.mastered.add(word.key); state.review.delete(word.key); $('#quizFeedback').textContent = '答对啦！+1 颗小星星 ⭐'; } else { button.classList.add('wrong'); state.review.add(word.key); $('#quizFeedback').textContent = `正确答案是“${word.chinese}”，已放进复习站。`; } save(); updateProgress(); renderReview(); renderModules($('#searchInput').value); $('#quizStars').textContent = Array.from({ length: 5 }, (_, i) => i < state.quizScore ? '★' : '☆').join(' '); setTimeout(() => { state.quizStep++; renderQuestion(); }, 1000); }

document.querySelectorAll('.tab').forEach(tab => tab.addEventListener('click', () => switchTab(tab.dataset.tab)));
$('#searchInput').addEventListener('input', e => renderModules(e.target.value));
$('#flashcard').addEventListener('click', () => { state.flipped = !state.flipped; $('#flashcard').classList.toggle('flipped', state.flipped); });
$('#speakWord').addEventListener('click', e => { e.stopPropagation(); speakCurrent(); }); $('#prevWord').addEventListener('click', () => changeCard(-1)); $('#nextWord').addEventListener('click', () => changeCard(1)); $('#needReview').addEventListener('click', () => markWord(false)); $('#knowWord').addEventListener('click', () => markWord(true));
document.querySelectorAll('[data-term]').forEach(button => button.addEventListener('click', () => switchTerm(button.dataset.term)));
$('#startLearning').addEventListener('click', () => chooseModule(modules[0].id)); $('#goQuiz').addEventListener('click', () => { switchTab('quiz'); startQuiz(); }); $('#startQuiz').addEventListener('click', startQuiz); $('#reviewAll').addEventListener('click', () => { const words = activeWords().filter(word => state.review.has(word.key)); if (!words.length) return toast('复习站暂时没有单词哦！'); switchTab('learn'); chooseModule(words[0].module.id, words); });
$('#soundToggle').addEventListener('click', () => { state.sound = !state.sound; $('#soundToggle').textContent = state.sound ? '🔊 发音' : '🔇 静音'; toast(state.sound ? '发音已开启' : '发音已关闭'); });
document.addEventListener('keydown', e => { if (e.key === 'ArrowRight') changeCard(1); if (e.key === 'ArrowLeft') changeCard(-1); if (e.key === ' ' && document.activeElement.tagName !== 'INPUT') { e.preventDefault(); $('#flashcard').click(); } });
switchTerm(currentTerm, false);
document.querySelector('.hero-copy .eyebrow').textContent = `福建省晋江市 · 外研版（三起）${termCatalog[currentTerm].label}`;
document.querySelectorAll('[data-term]').forEach(button => button.addEventListener('click', () => { document.querySelector('.hero-copy .eyebrow').textContent = `福建省晋江市 · 外研版（三起）${termCatalog[button.dataset.term].label}`; }));
